---
output:
  md_document:
    variant: markdown_github
---




```{r}

rm(list = ls()) # Clean your environment:
gc() # garbage collection - It can be useful to call gc after a large object has been removed, as this may prompt R to return memory to the operating system.
library(tidyverse)
list.files('code/', full.names = T, recursive = T) %>% .[grepl('.R', .)] %>% as.list() %>% walk(~source(.))
```

```{r}
CHOSEN_LOCATION <- "C:/Users/Harriet/Documents/DataSciencePractical2022"
fmxdat::make_project(FilePath = glue::glue("{CHOSEN_LOCATION}"), 
                     ProjNam = "21617023")

Texevier::create_template(directory = glue::glue("{CHOSEN_LOCATION}"), template_name = "Question1")
Texevier::create_template(directory = glue::glue("{CHOSEN_LOCATION}"), template_name = "Question2")
Texevier::create_template(directory = glue::glue("{CHOSEN_LOCATION}"), template_name = "Question3")
Texevier::create_template(directory = glue::glue("{CHOSEN_LOCATION}"), template_name = "Question4")
```

# Question 1: Evolution of Covid outbreak
```{r}
list.files('Question1/code/', full.names = T, recursive = T) %>% as.list() %>% walk(~source(.))
```


First, we want to investigate the misconception of the experience of African countries with Covid compared with other regions.
```{r}
ReadCovidDataCSV <- function(dataroot){
    library(readr)
owid_covid_data <- read_csv(dataroot)
}

CovidData <- ReadCovidDataCSV("Question1/data/Covid/owid-covid-data.csv")
View(CovidData)
```

```{r}
CovidData %>% group_by(location) %>% summarise(count=n()) %>% mean(.)
```
In the Our World in Data folder, we have data on 6 continents and many rows for N/A. We have approximately 800 periods, not consistent. We could isolate for 2020 per month from March.

```{r}
library(lubridate)
CovidAfricaPlotdf <- CovidData %>% mutate(month = month(date)) %>% select(continent, location, date, total_cases, month) %>% 
subset(date> "2020-01-01" & date < "2020-12-31") %>% na.omit(.) %>% group_by(continent, month) %>% summarise_at(vars(total_cases), ~mean(.))

CovidAfricaPlot <- CovidAfricaPlotdf %>% ggplot() + geom_col(aes(x=month, y=total_cases, fill=continent)) + labs(title="Evolution of Covid outbreak of total cases per month per continent in 2020") + ylab("Cumulative total cases") + xlab("Month in 2020")

?na.omit
CovidData %>% gather(Country,)
CovidData %>% select(continent, location, date, total_cases, month) 

%>% group_by(continent, date) %>% mutate(date=as.Date('%Y-%B'))
```

